//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.23 at 01:05:17 PM CET 
//

package com.leguide.backoffice.karaf.webservices.wsbrands.api.domain.wrapper.in.brands;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.leguide.backoffice.karaf.webservices.wsbrands.api.domain.jaxb.adapters.DateAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="activationDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="temporary_id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "name", "nameNormalized" })
@XmlRootElement(name = "alias")
public final class AliasInWrapper {

    @XmlElement(required = true)
    private String name;
    
    @XmlElement(required = true)
    private String nameNormalized;

    @XmlTransient
    private Date activationDate;

    @XmlTransient
    private Long temporaryId;

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the activationDate property.
     * 
     * @return possible object is {@link Date }
     * 
     */
    @XmlAttribute
    @XmlJavaTypeAdapter(DateAdapter.class)
    public Date getActivationDate() {
        return this.activationDate;
    }

    /**
     * Sets the value of the activationDate property.
     * 
     * @param value allowed object is {@link Date }
     * 
     */
    public void setActivationDate(Date value) {
        this.activationDate = value;
    }

    /**
     * Gets the value of the temporaryId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    @XmlAttribute
    public Long getTemporaryId() {
        return this.temporaryId;
    }

    /**
     * Sets the value of the temporaryId property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTemporaryId(Long value) {
        this.temporaryId = value;
    }

    public String getNameNormalized() {
        return nameNormalized;
    }

    public void setNameNormalized(String nameNormalized) {
        this.nameNormalized = nameNormalized;
    }

}
