//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.23 at 01:05:17 PM CET 
//

package com.leguide.backoffice.karaf.webservices.wsbrands.api.domain.wrapper.in.brands;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.leguide.backoffice.karaf.webservices.wsbrands.api.domain.jaxb.adapters.DateAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seoName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}alias" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="activationDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="temporary_id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "name", "seoName", "alias" })
@XmlRootElement(name = "brand")
public final class BrandInWrapper {

    @XmlElement(required = true)
    private String name;

    @XmlElement(required = false)
    private String seoName;

    private List<AliasInWrapper> alias;

    @XmlTransient
    private Date activationDate;

    @XmlTransient
    private Long temporaryId;

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the seoName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSeoName() {
        return this.seoName;
    }

    /**
     * Sets the value of the seoName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSeoName(String value) {
        this.seoName = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the alias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAlias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AliasInWrapper }
     * 
     * 
     */
    public List<AliasInWrapper> getAlias() {
        if (this.alias == null) {
            this.alias = new ArrayList<AliasInWrapper>();
        }
        return this.alias;
    }

    public void setAlias(List<AliasInWrapper> alias) {
        this.alias = alias;
    }

    /**
     * Gets the value of the activationDate property.
     * 
     * @return possible object is {@link Date }
     * 
     */
    @XmlAttribute
    @XmlJavaTypeAdapter(DateAdapter.class)
    public Date getActivationDate() {
        return this.activationDate;
    }

    /**
     * Sets the value of the activationDate property.
     * 
     * @param value allowed object is {@link Date }
     * 
     */
    public void setActivationDate(Date value) {
        this.activationDate = value;
    }

    /**
     * Gets the value of the temporaryId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    @XmlAttribute(name = "temporaryId")
    public Long getTemporaryId() {
        return this.temporaryId;
    }

    /**
     * Sets the value of the temporaryId property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTemporaryId(Long value) {
        this.temporaryId = value;
    }

}
