//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.23 at 01:05:17 PM CET 
//

package com.leguide.backoffice.karaf.webservices.wsbrands.api.domain.wrapper.in.brands;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.leguide.backoffice.karaf.webservices.wsbrands.api.pojo.in package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
//@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * com.leguide.backoffice.karaf.webservices.wsbrands.api.pojo.in
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AliasInWrapper }
     * 
     */
    public AliasInWrapper createAlias() {
        return new AliasInWrapper();
    }

    /**
     * Create an instance of {@link BrandInWrapper }
     * 
     */
    public BrandInWrapper createBrand() {
        return new BrandInWrapper();
    }

    /**
     * Create an instance of {@link BrandsListInWrapper }
     * 
     */
    public BrandsListInWrapper createBrandsList() {
        return new BrandsListInWrapper();
    }

}
