//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 04:35:15 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}request">
 *       &lt;sequence>
 *         &lt;element ref="{}kSite"/>
 *         &lt;element ref="{}kProtocol"/>
 *         &lt;element ref="{}kProdCount"/>
 *         &lt;element ref="{}kPage"/>
 *         &lt;element ref="{}kSort"/>
 *         &lt;element ref="{}kGroup"/>
 *         &lt;element ref="{}kOccasion"/>
 *         &lt;element ref="{}kDiscountMin"/>
 *         &lt;element ref="{}kDiscountMax"/>
 *         &lt;element ref="{}kPhp"/>
 *         &lt;element ref="{}kBaseID"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kSite",
    "kProtocol",
    "kProdCount",
    "kPage",
    "kSort",
    "kGroup",
    "kOccasion",
    "kDiscountMin",
    "kDiscountMax",
    "kPhp",
    "kBaseID",
    "kShop",
    "kDebug"
})
@XmlRootElement(name = "query")
public class ListOffersRequest
    extends Request
{

    protected int kSite;
    @XmlElement(required = true)
    protected String kProtocol;
    protected int kProdCount;
    protected int kPage;
    protected int kSort;
    protected int kGroup;
    protected int kOccasion;
    protected int kDiscountMin;
    protected int kDiscountMax;
    protected int kPhp;
    protected long kBaseID;
    //shop_id
    protected long kShop;
    //search engien debug mode: 1 or 0
    protected int kDebug;

    public int getkDebug() {
        return kDebug;
    }

    public void setkDebug(int kDebug) {
        this.kDebug = kDebug;
    }

    public long getkShop() {
        return kShop;
    }

    public void setkShop(long kShop) {
        this.kShop = kShop;
    }
    
    /**
     * Gets the value of the kSite property.
     * 
     */
    public int getKSite() {
        return kSite;
    }

    /**
     * Sets the value of the kSite property.
     * 
     */
    public void setKSite(int value) {
        this.kSite = value;
    }

    /**
     * Gets the value of the kProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKProtocol() {
        return kProtocol;
    }

    /**
     * Sets the value of the kProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKProtocol(String value) {
        this.kProtocol = value;
    }

    /**
     * Gets the value of the kProdCount property.
     * 
     */
    public int getKProdCount() {
        return kProdCount;
    }

    /**
     * Sets the value of the kProdCount property.
     * 
     */
    public void setKProdCount(int value) {
        this.kProdCount = value;
    }

    /**
     * Gets the value of the kPage property.
     * 
     */
    public int getKPage() {
        return kPage;
    }

    /**
     * Sets the value of the kPage property.
     * 
     */
    public void setKPage(int value) {
        this.kPage = value;
    }

    /**
     * Gets the value of the kSort property.
     * 
     */
    public int getKSort() {
        return kSort;
    }

    /**
     * Sets the value of the kSort property.
     * 
     */
    public void setKSort(int value) {
        this.kSort = value;
    }

    /**
     * Gets the value of the kGroup property.
     * 
     */
    public int getKGroup() {
        return kGroup;
    }

    /**
     * Sets the value of the kGroup property.
     * 
     */
    public void setKGroup(int value) {
        this.kGroup = value;
    }

    /**
     * Gets the value of the kOccasion property.
     * 
     */
    public int getKOccasion() {
        return kOccasion;
    }

    /**
     * Sets the value of the kOccasion property.
     * 
     */
    public void setKOccasion(int value) {
        this.kOccasion = value;
    }

    /**
     * Gets the value of the kDiscountMin property.
     * 
     */
    public int getKDiscountMin() {
        return kDiscountMin;
    }

    /**
     * Sets the value of the kDiscountMin property.
     * 
     */
    public void setKDiscountMin(int value) {
        this.kDiscountMin = value;
    }

    /**
     * Gets the value of the kDiscountMax property.
     * 
     */
    public int getKDiscountMax() {
        return kDiscountMax;
    }

    /**
     * Sets the value of the kDiscountMax property.
     * 
     */
    public void setKDiscountMax(int value) {
        this.kDiscountMax = value;
    }

    /**
     * Gets the value of the kPhp property.
     * 
     */
    public int getKPhp() {
        return kPhp;
    }

    /**
     * Sets the value of the kPhp property.
     * 
     */
    public void setKPhp(int value) {
        this.kPhp = value;
    }

    /**
     * Gets the value of the kBaseID property.
     * 
     */
    public long getKBaseID() {
        return kBaseID;
    }

    /**
     * Sets the value of the kBaseID property.
     * 
     */
    public void setKBaseID(long value) {
        this.kBaseID = value;
    }

    @Override
    public String toString() {
        return "ListOffersRequest [kSite=" + kSite + ", kProtocol=" + kProtocol + ", kProdCount=" + kProdCount
                + ", kPage=" + kPage + ", kSort=" + kSort + ", kGroup=" + kGroup + ", kOccasion=" + kOccasion
                + ", kDiscountMin=" + kDiscountMin + ", kDiscountMax=" + kDiscountMax + ", kPhp=" + kPhp + ", kBaseID="
                + kBaseID + "]";
    }

}
