//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 04:35:15 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.leguide.backoffice.karaf.webservices.client.engine.domain.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KFilter_QNAME = new QName("", "kFilter");
    private final static QName _KSort_QNAME = new QName("", "kSort");
    private final static QName _KZone_QNAME = new QName("", "kZone");
    private final static QName _KPays_QNAME = new QName("", "kPays");
    private final static QName _KPhp_QNAME = new QName("", "kPhp");
    private final static QName _KDateMin_QNAME = new QName("", "kDateMin");
    private final static QName _KDiscountMin_QNAME = new QName("", "kDiscountMin");
    private final static QName _KGroup_QNAME = new QName("", "kGroup");
    private final static QName _KCriteres_QNAME = new QName("", "kCriteres");
    private final static QName _KDiscountMax_QNAME = new QName("", "kDiscountMax");
    private final static QName _KShortLinks_QNAME = new QName("", "kShortLinks");
    private final static QName _KPriceMax_QNAME = new QName("", "kPriceMax");
    private final static QName _KOccasion_QNAME = new QName("", "kOccasion");
    private final static QName _KProduct_QNAME = new QName("", "kProduct");
    private final static QName _KWords_QNAME = new QName("", "kWords");
    private final static QName _KPage_QNAME = new QName("", "kPage");
    private final static QName _KSite_QNAME = new QName("", "kSite");
    private final static QName _KCat_QNAME = new QName("", "kCat");
    private final static QName _KPhonetic_QNAME = new QName("", "kPhonetic");
    private final static QName _KReviewsSources_QNAME = new QName("", "kReviewsSources");
    private final static QName _KOnlyCat_QNAME = new QName("", "kOnlyCat");
    private final static QName _KDateMax_QNAME = new QName("", "kDateMax");
    private final static QName _KBaseID_QNAME = new QName("", "kBaseID");
    private final static QName _KCatCount_QNAME = new QName("", "kCatCount");
    private final static QName _KFunc_QNAME = new QName("", "kFunc");
    private final static QName _KMark_QNAME = new QName("", "kMark");
    private final static QName _KProtocol_QNAME = new QName("", "kProtocol");
    private final static QName _KProdCount_QNAME = new QName("", "kProdCount");
    private final static QName _KMarkCount_QNAME = new QName("", "kMarkCount");
    private final static QName _KPriceMin_QNAME = new QName("", "kPriceMin");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.leguide.backoffice.karaf.webservices.client.engine.domain.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StartPageRequest }
     * 
     */
    public StartPageRequest createStartPageRequest() {
        return new StartPageRequest();
    }

    /**
     * Create an instance of {@link ListOffersRequest }
     * 
     */
    public ListOffersRequest createListOffersRequest() {
        return new ListOffersRequest();
    }

    /**
     * Create an instance of {@link ProductInfoRequest }
     * 
     */
    public ProductInfoRequest createProductInfoRequest() {
        return new ProductInfoRequest();
    }

    /**
     * Create an instance of {@link ProductsNetRequest }
     * 
     */
    public ProductsNetRequest createProductsNetRequest() {
        return new ProductsNetRequest();
    }

    /**
     * Create an instance of {@link GetOffersRequest }
     * 
     */
    public GetOffersRequest createGetOffersRequest() {
        return new GetOffersRequest();
    }
 
    /**
     * Create an instance of {@link InfoMagRequest }
     * 
     */
    public InfoMagRequest createInfoMagRequest() {
        return new InfoMagRequest();
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kFilter")
    public JAXBElement<Integer> createKFilter(Integer value) {
        return new JAXBElement<Integer>(_KFilter_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kSort")
    public JAXBElement<Integer> createKSort(Integer value) {
        return new JAXBElement<Integer>(_KSort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kZone")
    public JAXBElement<Integer> createKZone(Integer value) {
        return new JAXBElement<Integer>(_KZone_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kPays")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createKPays(String value) {
        return new JAXBElement<String>(_KPays_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kPhp")
    public JAXBElement<Integer> createKPhp(Integer value) {
        return new JAXBElement<Integer>(_KPhp_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kDateMin")
    public JAXBElement<String> createKDateMin(String value) {
        return new JAXBElement<String>(_KDateMin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kDiscountMin")
    public JAXBElement<Integer> createKDiscountMin(Integer value) {
        return new JAXBElement<Integer>(_KDiscountMin_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kGroup")
    public JAXBElement<Integer> createKGroup(Integer value) {
        return new JAXBElement<Integer>(_KGroup_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kCriteres")
    public JAXBElement<String> createKCriteres(String value) {
        return new JAXBElement<String>(_KCriteres_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kDiscountMax")
    public JAXBElement<Integer> createKDiscountMax(Integer value) {
        return new JAXBElement<Integer>(_KDiscountMax_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kShortLinks")
    public JAXBElement<Short> createKShortLinks(Short value) {
        return new JAXBElement<Short>(_KShortLinks_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kPriceMax")
    public JAXBElement<Float> createKPriceMax(Float value) {
        return new JAXBElement<Float>(_KPriceMax_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kOccasion")
    public JAXBElement<Integer> createKOccasion(Integer value) {
        return new JAXBElement<Integer>(_KOccasion_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kProduct")
    public JAXBElement<String> createKProduct(String value) {
        return new JAXBElement<String>(_KProduct_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kWords")
    public JAXBElement<String> createKWords(String value) {
        return new JAXBElement<String>(_KWords_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kPage")
    public JAXBElement<Integer> createKPage(Integer value) {
        return new JAXBElement<Integer>(_KPage_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kSite")
    public JAXBElement<Integer> createKSite(Integer value) {
        return new JAXBElement<Integer>(_KSite_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kCat")
    public JAXBElement<String> createKCat(String value) {
        return new JAXBElement<String>(_KCat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kPhonetic")
    public JAXBElement<Short> createKPhonetic(Short value) {
        return new JAXBElement<Short>(_KPhonetic_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kReviewsSources")
    public JAXBElement<Short> createKReviewsSources(Short value) {
        return new JAXBElement<Short>(_KReviewsSources_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kOnlyCat")
    public JAXBElement<Integer> createKOnlyCat(Integer value) {
        return new JAXBElement<Integer>(_KOnlyCat_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kDateMax")
    public JAXBElement<String> createKDateMax(String value) {
        return new JAXBElement<String>(_KDateMax_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kBaseID")
    public JAXBElement<Long> createKBaseID(Long value) {
        return new JAXBElement<Long>(_KBaseID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kCatCount")
    public JAXBElement<Integer> createKCatCount(Integer value) {
        return new JAXBElement<Integer>(_KCatCount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kFunc")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createKFunc(String value) {
        return new JAXBElement<String>(_KFunc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kMark")
    public JAXBElement<String> createKMark(String value) {
        return new JAXBElement<String>(_KMark_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kProtocol")
    public JAXBElement<String> createKProtocol(String value) {
        return new JAXBElement<String>(_KProtocol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kProdCount")
    public JAXBElement<Integer> createKProdCount(Integer value) {
        return new JAXBElement<Integer>(_KProdCount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kMarkCount")
    public JAXBElement<Integer> createKMarkCount(Integer value) {
        return new JAXBElement<Integer>(_KMarkCount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kPriceMin")
    public JAXBElement<Float> createKPriceMin(Float value) {
        return new JAXBElement<Float>(_KPriceMin_QNAME, Float.class, null, value);
    }

}
