//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 04:35:15 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}request">
 *       &lt;sequence>
 *         &lt;element ref="{}kSite"/>
 *         &lt;element ref="{}kProtocol"/>
 *         &lt;element ref="{}kProdCount"/>
 *         &lt;element ref="{}kPage"/>
 *         &lt;element ref="{}kSort"/>
 *         &lt;element ref="{}kGroup"/>
 *         &lt;element ref="{}kOccasion"/>
 *         &lt;element ref="{}kDiscountMin"/>
 *         &lt;element ref="{}kDiscountMax"/>
 *         &lt;element ref="{}kPhp"/>
 *         &lt;element ref="{}kCat"/>
 *         &lt;element ref="{}kMark"/>
 *         &lt;element ref="{}kWords"/>
 *         &lt;element ref="{}kPhonetic"/>
 *         &lt;element ref="{}kFilter"/>
 *         &lt;element ref="{}kPriceMin" minOccurs="0"/>
 *         &lt;element ref="{}kPriceMax" minOccurs="0"/>
 *         &lt;element ref="{}kMarkCount"/>
 *         &lt;element ref="{}kOnlyCat"/>
 *         &lt;element ref="{}kDateMin" minOccurs="0"/>
 *         &lt;element ref="{}kDateMax" minOccurs="0"/>
 *         &lt;element ref="{}kCatCount"/>
 *         &lt;element ref="{}kCriteres"/>
 *         &lt;element ref="{}kShortLinks"/>
 *         &lt;element ref="{}kReviewsSources"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kSite",
    "kProtocol",
    "kProdCount",
    "kPage",
    "kSort",
    "kGroup",
    "kOccasion",
    "kDiscountMin",
    "kDiscountMax",
    "kPhp",
    "kCat",
    "kMark",
    "kWords",
    "kPhonetic",
    "kFilter",
    "kPriceMin",
    "kPriceMax",
    "kMarkCount",
    "kOnlyCat",
    "kDateMin",
    "kDateMax",
    "kCatCount",
    "kCriteres",
    "kShortlinks",
    "kReviewsSources",
    "kDebug"
})
@XmlRootElement(name = "query")
public class ProductsNetRequest
    extends Request
{

    protected int kSite;
    @XmlElement(required = true)
    protected String kProtocol;
    protected Integer kProdCount;
    protected Integer kPage;
    protected int kSort;
    protected int kGroup;
    protected int kOccasion;
    protected int kDiscountMin;
    protected int kDiscountMax;
    protected int kPhp;
    @XmlElement(required = true)
    protected String kCat;
    @XmlElement(required = true)
    protected String kMark;
    @XmlElement(required = true)
    protected String kWords;
    protected short kPhonetic;
    protected int kFilter;
    protected Float kPriceMin;
    protected Float kPriceMax;
    protected int kMarkCount;
    protected int kOnlyCat;
    protected String kDateMin;
    protected String kDateMax;
    protected int kCatCount;
    @XmlElement(required = true)
    protected String kCriteres;
    protected short kShortlinks;
    protected short kReviewsSources;
    //search engien debug mode: 1 or 0
    protected int kDebug;

    public int getkDebug() {
        return kDebug;
    }

    public void setkDebug(int kDebug) {
        this.kDebug = kDebug;
    }


    /**
     * Gets the value of the kSite property.
     * 
     */
    public int getKSite() {
        return kSite;
    }

    /**
     * Sets the value of the kSite property.
     * 
     */
    public void setKSite(int value) {
        this.kSite = value;
    }

    /**
     * Gets the value of the kProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKProtocol() {
        return kProtocol;
    }

    /**
     * Sets the value of the kProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKProtocol(String value) {
        this.kProtocol = value;
    }

    /**
     * Gets the value of the kProdCount property.
     * 
     */
    public int getKProdCount() {
        return kProdCount;
    }

    /**
     * Sets the value of the kProdCount property.
     * 
     */
    public void setKProdCount(Integer value) {
        this.kProdCount = value;
    }

    /**
     * Gets the value of the kPage property.
     * 
     */
    public int getKPage() {
        return kPage;
    }

    /**
     * Sets the value of the kPage property.
     * 
     */
    public void setKPage(Integer value) {
        this.kPage = value;
    }

    /**
     * Gets the value of the kSort property.
     * 
     */
    public int getKSort() {
        return kSort;
    }

    /**
     * Sets the value of the kSort property.
     * 
     */
    public void setKSort(int value) {
        this.kSort = value;
    }

    /**
     * Gets the value of the kGroup property.
     * 
     */
    public int getKGroup() {
        return kGroup;
    }

    /**
     * Sets the value of the kGroup property.
     * 
     */
    public void setKGroup(int value) {
        this.kGroup = value;
    }

    /**
     * Gets the value of the kOccasion property.
     * 
     */
    public int getKOccasion() {
        return kOccasion;
    }

    /**
     * Sets the value of the kOccasion property.
     * 
     */
    public void setKOccasion(int value) {
        this.kOccasion = value;
    }

    /**
     * Gets the value of the kDiscountMin property.
     * 
     */
    public int getKDiscountMin() {
        return kDiscountMin;
    }

    /**
     * Sets the value of the kDiscountMin property.
     * 
     */
    public void setKDiscountMin(int value) {
        this.kDiscountMin = value;
    }

    /**
     * Gets the value of the kDiscountMax property.
     * 
     */
    public int getKDiscountMax() {
        return kDiscountMax;
    }

    /**
     * Sets the value of the kDiscountMax property.
     * 
     */
    public void setKDiscountMax(int value) {
        this.kDiscountMax = value;
    }

    /**
     * Gets the value of the kPhp property.
     * 
     */
    public int getKPhp() {
        return kPhp;
    }

    /**
     * Sets the value of the kPhp property.
     * 
     */
    public void setKPhp(int value) {
        this.kPhp = value;
    }

    /**
     * Gets the value of the kCat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKCat() {
        return kCat;
    }

    /**
     * Sets the value of the kCat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKCat(String value) {
        this.kCat = value;
    }

    /**
     * Gets the value of the kMark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKMark() {
        return kMark;
    }

    /**
     * Sets the value of the kMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKMark(String value) {
        this.kMark = value;
    }

    /**
     * Gets the value of the kWords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKWords() {
        return kWords;
    }

    /**
     * Sets the value of the kWords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKWords(String value) {
        this.kWords = value;
    }

    /**
     * Gets the value of the kPhonetic property.
     * 
     */
    public short getKPhonetic() {
        return kPhonetic;
    }

    /**
     * Sets the value of the kPhonetic property.
     * 
     */
    public void setKPhonetic(short value) {
        this.kPhonetic = value;
    }

    /**
     * Gets the value of the kFilter property.
     * 
     */
    public int getKFilter() {
        return kFilter;
    }

    /**
     * Sets the value of the kFilter property.
     * 
     */
    public void setKFilter(int value) {
        this.kFilter = value;
    }

    /**
     * Gets the value of the kPriceMin property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getKPriceMin() {
        return kPriceMin;
    }

    /**
     * Sets the value of the kPriceMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setKPriceMin(Float value) {
        this.kPriceMin = value;
    }

    /**
     * Gets the value of the kPriceMax property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getKPriceMax() {
        return kPriceMax;
    }

    /**
     * Sets the value of the kPriceMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setKPriceMax(Float value) {
        this.kPriceMax = value;
    }

    /**
     * Gets the value of the kMarkCount property.
     * 
     */
    public int getKMarkCount() {
        return kMarkCount;
    }

    /**
     * Sets the value of the kMarkCount property.
     * 
     */
    public void setKMarkCount(int value) {
        this.kMarkCount = value;
    }

    /**
     * Gets the value of the kOnlyCat property.
     * 
     */
    public int getKOnlyCat() {
        return kOnlyCat;
    }

    /**
     * Sets the value of the kOnlyCat property.
     * 
     */
    public void setKOnlyCat(int value) {
        this.kOnlyCat = value;
    }

    /**
     * Gets the value of the kDateMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKDateMin() {
        return kDateMin;
    }

    /**
     * Sets the value of the kDateMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKDateMin(String value) {
        this.kDateMin = value;
    }

    /**
     * Gets the value of the kDateMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKDateMax() {
        return kDateMax;
    }

    /**
     * Sets the value of the kDateMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKDateMax(String value) {
        this.kDateMax = value;
    }

    /**
     * Gets the value of the kCatCount property.
     * 
     */
    public int getKCatCount() {
        return kCatCount;
    }

    /**
     * Sets the value of the kCatCount property.
     * 
     */
    public void setKCatCount(int value) {
        this.kCatCount = value;
    }

    /**
     * Gets the value of the kCriteres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKCriteres() {
        return kCriteres;
    }

    /**
     * Sets the value of the kCriteres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKCriteres(String value) {
        this.kCriteres = value;
    }

    /**
     * Gets the value of the kShortLinks property.
     * 
     */
    public short getKShortlinks() {
        return kShortlinks;
    }

    /**
     * Sets the value of the kShortLinks property.
     * 
     */
    public void setKShortlinks(short value) {
        this.kShortlinks = value;
    }

    /**
     * Gets the value of the kReviewsSources property.
     * 
     */
    public short getKReviewsSources() {
        return kReviewsSources;
    }

    /**
     * Sets the value of the kReviewsSources property.
     * 
     */
    public void setKReviewsSources(short value) {
        this.kReviewsSources = value;
    }

    @Override
    public String toString() {
        return "ProductsNetRequest [kSite=" + kSite + ", kProtocol=" + kProtocol + ", kProdCount=" + kProdCount
                + ", kPage=" + kPage + ", kSort=" + kSort + ", kGroup=" + kGroup + ", kOccasion=" + kOccasion
                + ", kDiscountMin=" + kDiscountMin + ", kDiscountMax=" + kDiscountMax + ", kPhp=" + kPhp + ", kCat="
                + kCat + ", kMark=" + kMark + ", kWords=" + kWords + ", kPhonetic=" + kPhonetic + ", kFilter="
                + kFilter + ", kPriceMin=" + kPriceMin + ", kPriceMax=" + kPriceMax + ", kMarkCount=" + kMarkCount
                + ", kOnlyCat=" + kOnlyCat + ", kDateMin=" + kDateMin + ", kDateMax=" + kDateMax + ", kCatCount="
                + kCatCount + ", kCriteres=" + kCriteres + ", kShortlinks=" + kShortlinks + ", kReviewsSources="
                + kReviewsSources + "]";
    }

}
