//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 04:35:15 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}request">
 *       &lt;sequence>
 *         &lt;element ref="{}kProduct"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kProduct"
})
@XmlRootElement(name = "query")
public class ProductInfoRequest
    extends Request
{

    @XmlElement(required = true)
    protected String kProduct;

    /**
     * Gets the value of the kProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKProduct() {
        return kProduct;
    }

    /**
     * Sets the value of the kProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKProduct(String value) {
        this.kProduct = value;
    }

    @Override
    public String toString() {
        return "ProductInfoRequest [kProduct=" + kProduct + "]";
    }

}
