//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 04:35:15 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}request">
 *       &lt;sequence>
 *         &lt;element ref="{}kSite"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kSite"
})
@XmlRootElement(name = "query")
public class StartPageRequest
    extends Request
{

    protected int kSite;

    /**
     * Gets the value of the kSite property.
     * 
     */
    public int getKSite() {
        return kSite;
    }

    /**
     * Sets the value of the kSite property.
     * 
     */
    public void setKSite(int value) {
        this.kSite = value;
    }

}
