//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.18 at 12:17:06 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbgProdClic",
    "dbgProdWords"
})
@XmlRootElement(name = "DEBUG_LIST")
public class DEBUG {

    @XmlElement(name = "DBG_PROD_CLIC")
    protected int dbgProdClic;
    @XmlElement(name = "DBG_PROD_WORDS")
    protected String dbgProdWords;

    public int getDbgProdClic() {
        return dbgProdClic;
    }
    public void setDbgProdClic(int dbgProdClic) {
        this.dbgProdClic = dbgProdClic;
    }
    public String getDbgProdWords() {
        return dbgProdWords;
    }
    public void setDbgProdWords(String dbgProdWords) {
        this.dbgProdWords = dbgProdWords;
    }

}
