//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.18 at 12:17:06 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SHOP_ID"/>
 *         &lt;element ref="{}SHOP_LOGO"/>
 *         &lt;element ref="{}SHOP_NAME"/>
 *         &lt;element ref="{}SHOP_VARS"/>
 *         &lt;element ref="{}PROD_ID"/>
 *         &lt;element ref="{}OFFRE_PRICE"/>
 *         &lt;element ref="{}PROD_SOLDE"/>
 *         &lt;element ref="{}CAT_ID"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PLACE" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shopid",
    "shoplogo",
    "shopname",
    "shopvars",
    "prodid",
    "offreprice",
    "prodsolde",
    "catid"
})
@XmlRootElement(name = "OFFRE")
public class OFFRE {

    @XmlElement(name = "SHOP_ID")
    protected int shopid;
    @XmlElement(name = "SHOP_LOGO")
    protected int shoplogo;
    @XmlElement(name = "SHOP_NAME", required = true)
    protected String shopname;
    @XmlElement(name = "SHOP_VARS", required = true)
    protected String shopvars;
    @XmlElement(name = "PROD_ID", required = true)
    protected String prodid;
    @XmlElement(name = "OFFRE_PRICE")
    protected double offreprice;
    @XmlElement(name = "PROD_SOLDE")
    protected int prodsolde;
    @XmlElement(name = "CAT_ID")
    protected long catid;
    @XmlAttribute(name = "PLACE", required = true)
    protected int place;

    /**
     * Gets the value of the shopid property.
     * 
     */
    public int getSHOPID() {
        return shopid;
    }

    /**
     * Sets the value of the shopid property.
     * 
     */
    public void setSHOPID(int value) {
        this.shopid = value;
    }

    /**
     * Gets the value of the shoplogo property.
     * 
     */
    public int getSHOPLOGO() {
        return shoplogo;
    }

    /**
     * Sets the value of the shoplogo property.
     * 
     */
    public void setSHOPLOGO(int value) {
        this.shoplogo = value;
    }

    /**
     * Gets the value of the shopname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHOPNAME() {
        return shopname;
    }

    /**
     * Sets the value of the shopname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHOPNAME(String value) {
        this.shopname = value;
    }

    /**
     * Gets the value of the shopvars property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHOPVARS() {
        return shopvars;
    }

    /**
     * Sets the value of the shopvars property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHOPVARS(String value) {
        this.shopvars = value;
    }

    /**
     * Gets the value of the prodid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODID() {
        return prodid;
    }

    /**
     * Sets the value of the prodid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODID(String value) {
        this.prodid = value;
    }

    /**
     * Gets the value of the offreprice property.
     * 
     */
    public double getOFFREPRICE() {
        return offreprice;
    }

    /**
     * Sets the value of the offreprice property.
     * 
     */
    public void setOFFREPRICE(double value) {
        this.offreprice = value;
    }

    /**
     * Gets the value of the prodsolde property.
     * 
     */
    public int getPRODSOLDE() {
        return prodsolde;
    }

    /**
     * Sets the value of the prodsolde property.
     * 
     */
    public void setPRODSOLDE(int value) {
        this.prodsolde = value;
    }

    /**
     * Gets the value of the catid property.
     * 
     */
    public long getCATID() {
        return catid;
    }

    /**
     * Sets the value of the catid property.
     * 
     */
    public void setCATID(long value) {
        this.catid = value;
    }

    /**
     * Gets the value of the place property.
     * 
     */
    public int getPLACE() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     */
    public void setPLACE(int value) {
        this.place = value;
    }

}
