//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.18 at 12:17:06 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PRICE_MIN"/>
 *         &lt;element ref="{}PRICE_MAX"/>
 *         &lt;element ref="{}PRODUCT_COUNT"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PLACE" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pricemin",
    "pricemax",
    "productcount"
})
@XmlRootElement(name = "PRICE")
public class PRICE {

    @XmlElement(name = "PRICE_MIN")
    protected float pricemin;
    @XmlElement(name = "PRICE_MAX")
    protected float pricemax;
    @XmlElement(name = "PRODUCT_COUNT")
    protected long productcount;
    @XmlAttribute(name = "PLACE", required = true)
    protected int place;

    /**
     * Gets the value of the pricemin property.
     * 
     */
    public float getPRICEMIN() {
        return pricemin;
    }

    /**
     * Sets the value of the pricemin property.
     * 
     */
    public void setPRICEMIN(float value) {
        this.pricemin = value;
    }

    /**
     * Gets the value of the pricemax property.
     * 
     */
    public float getPRICEMAX() {
        return pricemax;
    }

    /**
     * Sets the value of the pricemax property.
     * 
     */
    public void setPRICEMAX(float value) {
        this.pricemax = value;
    }

    /**
     * Gets the value of the productcount property.
     * 
     */
    public long getPRODUCTCOUNT() {
        return productcount;
    }

    /**
     * Sets the value of the productcount property.
     * 
     */
    public void setPRODUCTCOUNT(long value) {
        this.productcount = value;
    }

    /**
     * Gets the value of the place property.
     * 
     */
    public int getPLACE() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     */
    public void setPLACE(int value) {
        this.place = value;
    }

}
