//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.18 at 12:17:06 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.response;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{com.leguide.mobile.xsd.response}Response">
 *       &lt;sequence>
 *         &lt;element ref="{}PROTOCOL_VERSION"/>
 *         &lt;element ref="{}QUERY_ID"/>
 *         &lt;element ref="{}EXACT_MATCH"/>
 *         &lt;element ref="{}WORD_COUNT"/>
 *         &lt;element ref="{}PRODUCT_COUNT"/>
 *         &lt;element ref="{}OFFRE_COUNT"/>
 *         &lt;element ref="{}NEUF_COUNT"/>
 *         &lt;element ref="{}OCCASE_COUNT"/>
 *         &lt;element ref="{}SOLDE_COUNT"/>
 *         &lt;element ref="{}PRIVE_COUNT"/>
 *         &lt;element ref="{}FREE_FP_COUNT"/>
 *         &lt;element ref="{}BARRE_COUNT"/>
 *         &lt;element ref="{}SHOP_COUNT"/>
 *         &lt;element ref="{}CAT_COUNT"/>
 *         &lt;element ref="{}PAGE_COUNT"/>
 *         &lt;element ref="{}PRICE_LIST_COUNT"/>
 *         &lt;element ref="{}PRICE_LIST"/>
 *         &lt;element ref="{}MARK_COUNT"/>
 *         &lt;element ref="{}MARK_LIST_COUNT"/>
 *         &lt;element ref="{}MARK_LIST"/>
 *         &lt;element ref="{}CRIT_BAR_LIST_COUNT"/>
 *         &lt;element ref="{}CRIT_BAR_LIST"/>
 *         &lt;element ref="{}CRIT_LIST_COUNT"/>
 *         &lt;element ref="{}CRIT_LIST"/>
 *         &lt;element ref="{}CARACT_LIST_COUNT"/>
 *         &lt;element ref="{}CARACT_LIST"/>
 *         &lt;element ref="{}POPULAR_CAT_LIST_COUNT"/>
 *         &lt;element ref="{}POPULAR_CAT_LIST"/>
 *         &lt;element ref="{}PRODUCT_LIST_COUNT"/>
 *         &lt;element ref="{}PRODUCT_LIST"/>
 *         &lt;element ref="{}UNIVERS_LIST_COUNT"/>
 *         &lt;element ref="{}UNIVERS_LIST"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "protocolversion",
    "queryid",
    "exactmatch",
    "wordcount",
    "productcount",
    "catnamenormal",
    "offrecount",
    "neufcount",
    "occasecount",
    "soldecount",
    "privecount",
    "freefpcount",
    "barrecount",
    "shopcount",
    "catcount",
    "pagecount",
    "pricemin",
    "pricemax",
    "pricelistcount",
    "pricelist",
    "markcount",
    "marklistcount",
    "marklist",
    "critbarlistcount",
    "critbarlist",
    "critlistcount",
    "critlist",
    "caractlistcount",
    "caractlist",
    "popularcatlistcount",
    "popularcatlist",
    "productlistcount",
    "productlist",
    "universlistcount",
    "universlist"
})
@XmlRootElement(name = "RESULTATPN")
public class RESULTATPN
    extends Response
{

    @XmlElement(name = "PROTOCOL_VERSION", required = true)
    protected BigDecimal protocolversion;
    @XmlElement(name = "QUERY_ID", required = true)
    protected BigInteger queryid;
    @XmlElement(name = "EXACT_MATCH", required = true)
    protected EXACTMATCH exactmatch;
    @XmlElement(name = "WORD_COUNT")
    protected int wordcount;
    @XmlElement(name = "PRODUCT_COUNT")
    protected long productcount;
    @XmlElement(name = "OFFRE_COUNT")
    protected long offrecount;
    @XmlElement(name = "NEUF_COUNT")
    protected int neufcount;
    @XmlElement(name = "OCCASE_COUNT")
    protected int occasecount;
    @XmlElement(name = "SOLDE_COUNT")
    protected int soldecount;
    @XmlElement(name = "PRIVE_COUNT")
    protected int privecount;
    @XmlElement(name = "FREE_FP_COUNT")
    protected int freefpcount;
    @XmlElement(name = "BARRE_COUNT")
    protected int barrecount;
    @XmlElement(name = "SHOP_COUNT")
    protected int shopcount;
    @XmlElement(name = "CAT_COUNT")
    protected int catcount;
    @XmlElement(name = "CAT_NAME_NORMAL")
    protected String catnamenormal;
    @XmlElement(name = "PAGE_COUNT")
    protected int pagecount;
    @XmlElement(name = "PRICE_MIN")
    protected float pricemin;
    @XmlElement(name = "PRICE_MAX")
    protected float pricemax;
    @XmlElement(name = "PRICE_LIST_COUNT")
    protected int pricelistcount;
    @XmlElement(name = "PRICE_LIST", required = true)
    protected PRICELIST pricelist;
    @XmlElement(name = "MARK_COUNT")
    protected int markcount;
    @XmlElement(name = "MARK_LIST_COUNT")
    protected int marklistcount;
    @XmlElement(name = "MARK_LIST", required = true)
    protected MARKLIST marklist;
    @XmlElement(name = "CRIT_BAR_LIST_COUNT")
    protected int critbarlistcount;
    @XmlElement(name = "CRIT_BAR_LIST", required = true)
    protected CRITBARLIST critbarlist;
    @XmlElement(name = "CRIT_LIST_COUNT")
    protected int critlistcount;
    @XmlElement(name = "CRIT_LIST", required = true)
    protected CRITLIST critlist;
    @XmlElement(name = "CARACT_LIST_COUNT")
    protected int caractlistcount;
    @XmlElement(name = "CARACT_LIST", required = true)
    protected CARACTLIST caractlist;
    @XmlElement(name = "POPULAR_CAT_LIST_COUNT")
    protected int popularcatlistcount;
    @XmlElement(name = "POPULAR_CAT_LIST", required = true)
    protected POPULARCATLIST popularcatlist;
    @XmlElement(name = "PRODUCT_LIST_COUNT")
    protected int productlistcount;
    @XmlElement(name = "PRODUCT_LIST", required = true)
    protected PRODUCTLIST productlist;
    @XmlElement(name = "UNIVERS_LIST_COUNT")
    protected int universlistcount;
    @XmlElement(name = "UNIVERS_LIST", required = true)
    protected UNIVERSLIST universlist;

    /**
     * Gets the value of the protocolversion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPROTOCOLVERSION() {
        return protocolversion;
    }

    /**
     * Sets the value of the protocolversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPROTOCOLVERSION(BigDecimal value) {
        this.protocolversion = value;
    }

    /**
     * Gets the value of the queryid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQUERYID() {
        return queryid;
    }

    /**
     * Sets the value of the queryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQUERYID(BigInteger value) {
        this.queryid = value;
    }

    /**
     * Gets the value of the exactmatch property.
     * 
     * @return
     *     possible object is
     *     {@link EXACTMATCH }
     *     
     */
    public EXACTMATCH getEXACTMATCH() {
        return exactmatch;
    }

    /**
     * Sets the value of the exactmatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXACTMATCH }
     *     
     */
    public void setEXACTMATCH(EXACTMATCH value) {
        this.exactmatch = value;
    }

    /**
     * Gets the value of the wordcount property.
     * 
     */
    public int getWORDCOUNT() {
        return wordcount;
    }

    /**
     * Sets the value of the wordcount property.
     * 
     */
    public void setWORDCOUNT(int value) {
        this.wordcount = value;
    }

    /**
     * Gets the value of the productcount property.
     * 
     */
    public long getPRODUCTCOUNT() {
        return productcount;
    }

    /**
     * Sets the value of the productcount property.
     * 
     */
    public void setPRODUCTCOUNT(long value) {
        this.productcount = value;
    }

    /**
     * Gets the value of the offrecount property.
     * 
     */
    public long getOFFRECOUNT() {
        return offrecount;
    }

    /**
     * Sets the value of the offrecount property.
     * 
     */
    public void setOFFRECOUNT(long value) {
        this.offrecount = value;
    }

    /**
     * Gets the value of the neufcount property.
     * 
     */
    public int getNEUFCOUNT() {
        return neufcount;
    }

    /**
     * Sets the value of the neufcount property.
     * 
     */
    public void setNEUFCOUNT(int value) {
        this.neufcount = value;
    }

    /**
     * Gets the value of the occasecount property.
     * 
     */
    public int getOCCASECOUNT() {
        return occasecount;
    }

    /**
     * Sets the value of the occasecount property.
     * 
     */
    public void setOCCASECOUNT(int value) {
        this.occasecount = value;
    }

    /**
     * Gets the value of the soldecount property.
     * 
     */
    public int getSOLDECOUNT() {
        return soldecount;
    }

    /**
     * Sets the value of the soldecount property.
     * 
     */
    public void setSOLDECOUNT(int value) {
        this.soldecount = value;
    }

    /**
     * Gets the value of the privecount property.
     * 
     */
    public int getPRIVECOUNT() {
        return privecount;
    }

    /**
     * Sets the value of the privecount property.
     * 
     */
    public void setPRIVECOUNT(int value) {
        this.privecount = value;
    }

    /**
     * Gets the value of the freefpcount property.
     * 
     */
    public int getFREEFPCOUNT() {
        return freefpcount;
    }

    /**
     * Sets the value of the freefpcount property.
     * 
     */
    public void setFREEFPCOUNT(int value) {
        this.freefpcount = value;
    }

    /**
     * Gets the value of the barrecount property.
     * 
     */
    public int getBARRECOUNT() {
        return barrecount;
    }

    /**
     * Sets the value of the barrecount property.
     * 
     */
    public void setBARRECOUNT(int value) {
        this.barrecount = value;
    }

    /**
     * Gets the value of the shopcount property.
     * 
     */
    public int getSHOPCOUNT() {
        return shopcount;
    }

    /**
     * Sets the value of the shopcount property.
     * 
     */
    public void setSHOPCOUNT(int value) {
        this.shopcount = value;
    }

    /**
     * Gets the value of the catcount property.
     * 
     */
    public int getCATCOUNT() {
        return catcount;
    }

    /**
     * Sets the value of the catcount property.
     * 
     */
    public void setCATCOUNT(int value) {
        this.catcount = value;
    }

    /**
     * Gets the value of the pagecount property.
     * 
     */
    public int getPAGECOUNT() {
        return pagecount;
    }

    /**
     * Sets the value of the pagecount property.
     * 
     */
    public void setPAGECOUNT(int value) {
        this.pagecount = value;
    }

    /**
     * Gets the value of the pricelistcount property.
     * 
     */
    public int getPRICELISTCOUNT() {
        return pricelistcount;
    }

    /**
     * Sets the value of the pricelistcount property.
     * 
     */
    public void setPRICELISTCOUNT(int value) {
        this.pricelistcount = value;
    }

    /**
     * Gets the value of the pricelist property.
     * 
     * @return
     *     possible object is
     *     {@link PRICELIST }
     *     
     */
    public PRICELIST getPRICELIST() {
        return pricelist;
    }

    /**
     * Sets the value of the pricelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICELIST }
     *     
     */
    public void setPRICELIST(PRICELIST value) {
        this.pricelist = value;
    }

    /**
     * Gets the value of the markcount property.
     * 
     */
    public int getMARKCOUNT() {
        return markcount;
    }

    /**
     * Sets the value of the markcount property.
     * 
     */
    public void setMARKCOUNT(int value) {
        this.markcount = value;
    }

    /**
     * Gets the value of the marklistcount property.
     * 
     */
    public int getMARKLISTCOUNT() {
        return marklistcount;
    }

    /**
     * Sets the value of the marklistcount property.
     * 
     */
    public void setMARKLISTCOUNT(int value) {
        this.marklistcount = value;
    }

    /**
     * Gets the value of the marklist property.
     * 
     * @return
     *     possible object is
     *     {@link MARKLIST }
     *     
     */
    public MARKLIST getMARKLIST() {
        return marklist;
    }

    /**
     * Sets the value of the marklist property.
     * 
     * @param value
     *     allowed object is
     *     {@link MARKLIST }
     *     
     */
    public void setMARKLIST(MARKLIST value) {
        this.marklist = value;
    }

    /**
     * Gets the value of the critbarlistcount property.
     * 
     */
    public int getCRITBARLISTCOUNT() {
        return critbarlistcount;
    }

    /**
     * Sets the value of the critbarlistcount property.
     * 
     */
    public void setCRITBARLISTCOUNT(int value) {
        this.critbarlistcount = value;
    }

    /**
     * Gets the value of the critbarlist property.
     * 
     * @return
     *     possible object is
     *     {@link CRITBARLIST }
     *     
     */
    public CRITBARLIST getCRITBARLIST() {
        return critbarlist;
    }

    /**
     * Sets the value of the critbarlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRITBARLIST }
     *     
     */
    public void setCRITBARLIST(CRITBARLIST value) {
        this.critbarlist = value;
    }

    /**
     * Gets the value of the critlistcount property.
     * 
     */
    public int getCRITLISTCOUNT() {
        return critlistcount;
    }

    /**
     * Sets the value of the critlistcount property.
     * 
     */
    public void setCRITLISTCOUNT(int value) {
        this.critlistcount = value;
    }

    /**
     * Gets the value of the critlist property.
     * 
     * @return
     *     possible object is
     *     {@link CRITLIST }
     *     
     */
    public CRITLIST getCRITLIST() {
        return critlist;
    }

    /**
     * Sets the value of the critlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRITLIST }
     *     
     */
    public void setCRITLIST(CRITLIST value) {
        this.critlist = value;
    }

    /**
     * Gets the value of the caractlistcount property.
     * 
     */
    public int getCARACTLISTCOUNT() {
        return caractlistcount;
    }

    /**
     * Sets the value of the caractlistcount property.
     * 
     */
    public void setCARACTLISTCOUNT(int value) {
        this.caractlistcount = value;
    }

    /**
     * Gets the value of the caractlist property.
     * 
     * @return
     *     possible object is
     *     {@link CARACTLIST }
     *     
     */
    public CARACTLIST getCARACTLIST() {
        return caractlist;
    }

    /**
     * Sets the value of the caractlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link CARACTLIST }
     *     
     */
    public void setCARACTLIST(CARACTLIST value) {
        this.caractlist = value;
    }

    /**
     * Gets the value of the popularcatlistcount property.
     * 
     */
    public int getPOPULARCATLISTCOUNT() {
        return popularcatlistcount;
    }

    /**
     * Sets the value of the popularcatlistcount property.
     * 
     */
    public void setPOPULARCATLISTCOUNT(int value) {
        this.popularcatlistcount = value;
    }

    /**
     * Gets the value of the popularcatlist property.
     * 
     * @return
     *     possible object is
     *     {@link POPULARCATLIST }
     *     
     */
    public POPULARCATLIST getPOPULARCATLIST() {
        return popularcatlist;
    }

    /**
     * Sets the value of the popularcatlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link POPULARCATLIST }
     *     
     */
    public void setPOPULARCATLIST(POPULARCATLIST value) {
        this.popularcatlist = value;
    }

    /**
     * Gets the value of the productlistcount property.
     * 
     */
    public int getPRODUCTLISTCOUNT() {
        return productlistcount;
    }

    /**
     * Sets the value of the productlistcount property.
     * 
     */
    public void setPRODUCTLISTCOUNT(int value) {
        this.productlistcount = value;
    }

    /**
     * Gets the value of the productlist property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTLIST }
     *     
     */
    public PRODUCTLIST getPRODUCTLIST() {
        return productlist;
    }

    /**
     * Sets the value of the productlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTLIST }
     *     
     */
    public void setPRODUCTLIST(PRODUCTLIST value) {
        this.productlist = value;
    }

    /**
     * Gets the value of the universlistcount property.
     * 
     */
    public int getUNIVERSLISTCOUNT() {
        return universlistcount;
    }

    /**
     * Sets the value of the universlistcount property.
     * 
     */
    public void setUNIVERSLISTCOUNT(int value) {
        this.universlistcount = value;
    }

    /**
     * Gets the value of the universlist property.
     * 
     * @return
     *     possible object is
     *     {@link UNIVERSLIST }
     *     
     */
    public UNIVERSLIST getUNIVERSLIST() {
        return universlist;
    }

    /**
     * Sets the value of the universlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link UNIVERSLIST }
     *     
     */
    public void setUNIVERSLIST(UNIVERSLIST value) {
        this.universlist = value;
    }

    public String getCATNAMENORMAL() {
        return catnamenormal;
    }

    public void setCATNAMENORMAL(String catnamenormal) {
        this.catnamenormal = catnamenormal;
    }

    public float getPRICEMIN() {
        return pricemin;
    }

    public void setPRICEMIN(float pricemin) {
        this.pricemin = pricemin;
    }

    public float getPRICEMAX() {
        return pricemax;
    }

    public void setPRICEMAX(float pricemax) {
        this.pricemax = pricemax;
    }

}
