//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.18 at 12:17:06 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{com.leguide.mobile.xsd.response}Response">
 *       &lt;sequence>
 *         &lt;element ref="{}TOTAL_PRODUCT_COUNT"/>
 *         &lt;element ref="{}SHOP_TOTAL_OFFRE_COUNT"/>
 *         &lt;element ref="{}SHOP_ID"/>
 *         &lt;element ref="{}SHOPSITE_ID"/>
 *         &lt;element ref="{}SHOP_NAME"/>
 *         &lt;element ref="{}SHOP_FLAG"/>
 *         &lt;element ref="{}CAT_LIST_COUNT"/>
 *         &lt;element ref="{}CAT_LIST"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalProductCount",
    "totalShopOfferCount",
    "shopId",
    "shopSiteId",
    "shopName",
    "shopFlag",
    "catlistcount",
    "catlist"
})
@XmlRootElement(name = "RESULTATInfoMag")
public class RESULTATInfoMag extends Response {

    @XmlElement(name = "TOTAL_PRODUCT_COUNT")
    protected long totalProductCount;
    @XmlElement(name = "SHOP_TOTAL_OFFRE_COUNT")
    protected long totalShopOfferCount;
    @XmlElement(name = "SHOP_ID")
    protected Long shopId;
    @XmlElement(name = "SHOPSITE_ID")
    protected Long shopSiteId;
    @XmlElement(name = "SHOP_NAME")
    protected String shopName;
    @XmlElement(name = "SHOP_FLAG")
    protected int shopFlag;
    @XmlElement(name = "CAT_LIST_COUNT")
    protected int catlistcount;
    @XmlElement(name = "CAT_LIST", required = true)
    protected CATLIST catlist;

    public long getTotalProductCount() {
        return totalProductCount;
    }
    public void setTotalProductCount(long totalProductCount) {
        this.totalProductCount = totalProductCount;
    }
    public long getTotalShopOfferCount() {
        return totalShopOfferCount;
    }
    public void setTotalShopOfferCount(long totalShopOfferCount) {
        this.totalShopOfferCount = totalShopOfferCount;
    }
    public Long getShopId() {
        return shopId;
    }
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }
    public Long getShopSiteId() {
        return shopSiteId;
    }
    public void setShopSiteId(Long shopSiteId) {
        this.shopSiteId = shopSiteId;
    }
    public String getShopName() {
        return shopName;
    }
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }
    public int getShopFlag() {
        return shopFlag;
    }
    public void setShopFlag(int shopFlag) {
        this.shopFlag = shopFlag;
    }
    public int getCatlistcount() {
        return catlistcount;
    }
    public void setCatlistcount(int catlistcount) {
        this.catlistcount = catlistcount;
    }
    public CATLIST getCatlist() {
        return catlist;
    }
    public void setCatlist(CATLIST catlist) {
        this.catlist = catlist;
    }
    @Override
    public String toString() {
        return "RESULTATInfoMag [totalProductCount=" + totalProductCount + ", totalShopOfferCount="
                + totalShopOfferCount + ", " + (shopId != null ? "shopId=" + shopId + ", " : "")
                + (shopSiteId != null ? "shopSiteId=" + shopSiteId + ", " : "")
                + (shopName != null ? "shopName=" + shopName + ", " : "") + "shopFlag=" + shopFlag + ", catlistcount="
                + catlistcount + ", " + (catlist != null ? "catlist=" + catlist : "") + "]";
    }
}
