//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.18 at 12:17:06 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}COUNT"/>
 *         &lt;element ref="{}AVERAGE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "count",
    "average"
})
@XmlRootElement(name = "REVIEWS")
public class REVIEWS {

    @XmlElement(name = "COUNT")
    protected int count;
    @XmlElement(name = "AVERAGE")
    protected int average;

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCOUNT() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCOUNT(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the average property.
     * 
     */
    public int getAVERAGE() {
        return average;
    }

    /**
     * Sets the value of the average property.
     * 
     */
    public void setAVERAGE(int value) {
        this.average = value;
    }

}
