//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.18 at 12:17:06 PM CET 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FIELD"/>
 *         &lt;element ref="{}START"/>
 *         &lt;element ref="{}LENGTH"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PLACE" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "field",
    "start",
    "length"
})
@XmlRootElement(name = "WORD")
public class WORD {

    @XmlElement(name = "FIELD")
    protected int field;
    @XmlElement(name = "START")
    protected int start;
    @XmlElement(name = "LENGTH")
    protected int length;
    @XmlAttribute(name = "PLACE", required = true)
    protected int place;

    /**
     * Gets the value of the field property.
     * 
     */
    public int getFIELD() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     */
    public void setFIELD(int value) {
        this.field = value;
    }

    /**
     * Gets the value of the start property.
     * 
     */
    public int getSTART() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     */
    public void setSTART(int value) {
        this.start = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public int getLENGTH() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLENGTH(int value) {
        this.length = value;
    }

    /**
     * Gets the value of the place property.
     * 
     */
    public int getPLACE() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     */
    public void setPLACE(int value) {
        this.place = value;
    }

}
