//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.22 at 05:45:26 PM CEST 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.response.listeOffers;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.leguide.backoffice.karaf.webservices.client.engine.domain.response.listeOffers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PRODEUROFP_QNAME = new QName("", "PROD_EURO_FP");
    private final static QName _SHOPVARS_QNAME = new QName("", "SHOP_VARS");
    private final static QName _CARACTLISTCOUNT_QNAME = new QName("", "CARACT_LIST_COUNT");
    private final static QName _SHOPMEDIATION_QNAME = new QName("", "SHOP_MEDIATION");
    private final static QName _SHOPCOUNT_QNAME = new QName("", "SHOP_COUNT");
    private final static QName _PRODDISPO_QNAME = new QName("", "PROD_DISPO");
    private final static QName _PRODREF_QNAME = new QName("", "PROD_REF");
    private final static QName _PRODUCTLISTCOUNT_QNAME = new QName("", "PRODUCT_LIST_COUNT");
    private final static QName _BARRECOUNT_QNAME = new QName("", "BARRE_COUNT");
    private final static QName _SHOPPAYS_QNAME = new QName("", "SHOP_PAYS");
    private final static QName _GROUPSOLDE_QNAME = new QName("", "GROUP_SOLDE");
    private final static QName _PRODPRIVE_QNAME = new QName("", "PROD_PRIVE");
    private final static QName _SHOPNAME_QNAME = new QName("", "SHOP_NAME");
    private final static QName _QUERYID_QNAME = new QName("", "QUERY_ID");
    private final static QName _PRODWITHCARAC_QNAME = new QName("", "PROD_WITH_CARAC");
    private final static QName _SHOPLOGO_QNAME = new QName("", "SHOP_LOGO");
    private final static QName _CARACTNAME_QNAME = new QName("", "CARACT_NAME");
    private final static QName _CRITLISTCOUNT_QNAME = new QName("", "CRIT_LIST_COUNT");
    private final static QName _SHOPLABELVALID_QNAME = new QName("", "SHOP_LABEL_VALID");
    private final static QName _SHOPGLOBAL_QNAME = new QName("", "SHOP_GLOBAL");
    private final static QName _OCCASECOUNT_QNAME = new QName("", "OCCASE_COUNT");
    private final static QName _PRODINTLFP_QNAME = new QName("", "PROD_INTL_FP");
    private final static QName _OFFRECOUNT_QNAME = new QName("", "OFFRE_COUNT");
    private final static QName _SHOPID_QNAME = new QName("", "SHOP_ID");
    private final static QName _PRODD3E_QNAME = new QName("", "PROD_D3E");
    private final static QName _PRODBASEID_QNAME = new QName("", "PROD_BASE_ID");
    private final static QName _MARKCOUNT_QNAME = new QName("", "MARK_COUNT");
    private final static QName _MARKLISTCOUNT_QNAME = new QName("", "MARK_LIST_COUNT");
    private final static QName _PRODINTLDEVISE_QNAME = new QName("", "PROD_INTL_DEVISE");
    private final static QName _PRODDESCRIPTION_QNAME = new QName("", "PROD_DESCRIPTION");
    private final static QName _PRICELISTCOUNT_QNAME = new QName("", "PRICE_LIST_COUNT");
    private final static QName _CATURL_QNAME = new QName("", "CAT_URL");
    private final static QName _CARACTVALUE_QNAME = new QName("", "CARACT_VALUE");
    private final static QName _PRODSOLDE_QNAME = new QName("", "PROD_SOLDE");
    private final static QName _PRODINTLPRICE_QNAME = new QName("", "PROD_INTL_PRICE");
    private final static QName _PRODUCTCOUNT_QNAME = new QName("", "PRODUCT_COUNT");
    private final static QName _NEUFCOUNT_QNAME = new QName("", "NEUF_COUNT");
    private final static QName _CARACTID_QNAME = new QName("", "CARACT_ID");
    private final static QName _PRIVECOUNT_QNAME = new QName("", "PRIVE_COUNT");
    private final static QName _PRODCATSHOP_QNAME = new QName("", "PROD_CAT_SHOP");
    private final static QName _PRODMARK_QNAME = new QName("", "PROD_MARK");
    private final static QName _PRODID_QNAME = new QName("", "PROD_ID");
    private final static QName _CATSINGLENAME_QNAME = new QName("", "CAT_SINGLE_NAME");
    private final static QName _PRODMASQUE_QNAME = new QName("", "PROD_MASQUE");
    private final static QName _PRODREFINTERNE_QNAME = new QName("", "PROD_REF_INTERNE");
    private final static QName _CATIDINTERNE_QNAME = new QName("", "CAT_ID_INTERNE");
    private final static QName _SOLDECOUNT_QNAME = new QName("", "SOLDE_COUNT");
    private final static QName _PAGECOUNT_QNAME = new QName("", "PAGE_COUNT");
    private final static QName _CATID_QNAME = new QName("", "CAT_ID");
    private final static QName _PRODURL_QNAME = new QName("", "PROD_URL");
    private final static QName _PRODGARANTIE_QNAME = new QName("", "PROD_GARANTIE");
    private final static QName _PRODDESIGNATION_QNAME = new QName("", "PROD_DESIGNATION");
    private final static QName _PRICEMIN_QNAME = new QName("", "PRICE_MIN");
    private final static QName _PRODEURODISCOUNT_QNAME = new QName("", "PROD_EURO_DISCOUNT");
    private final static QName _PRODOCCASION_QNAME = new QName("", "PROD_OCCASION");
    private final static QName _PRICEMAX_QNAME = new QName("", "PRICE_MAX");
    private final static QName _PRODEAN13_QNAME = new QName("", "PROD_EAN13");
    private final static QName _PRODEUROPRICE_QNAME = new QName("", "PROD_EURO_PRICE");
    private final static QName _PRODDISPONAME_QNAME = new QName("", "PROD_DISPO_NAME");
    private final static QName _TOTALPRODUCTCOUNT_QNAME = new QName("", "TOTAL_PRODUCT_COUNT");
    private final static QName _PRODIMG_QNAME = new QName("", "PROD_IMG");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.leguide.backoffice.karaf.webservices.client.engine.domain.response.listeOffers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RESULTAT }
     * 
     */
    public RESULTAT createRESULTAT() {
        return new RESULTAT();
    }

    /**
     * Create an instance of {@link PRICE }
     * 
     */
    public PRICE createPRICE() {
        return new PRICE();
    }

    /**
     * Create an instance of {@link PRODEXTRAS }
     * 
     */
    public PRODEXTRAS createPRODEXTRAS() {
        return new PRODEXTRAS();
    }

    /**
     * Create an instance of {@link PRICELIST }
     * 
     */
    public PRICELIST createPRICELIST() {
        return new PRICELIST();
    }

    /**
     * Create an instance of {@link MARKLIST }
     * 
     */
    public MARKLIST createMARKLIST() {
        return new MARKLIST();
    }

    /**
     * Create an instance of {@link CARACTLIST }
     * 
     */
    public CARACTLIST createCARACTLIST() {
        return new CARACTLIST();
    }

    /**
     * Create an instance of {@link PRODUCTLIST }
     * 
     */
    public PRODUCTLIST createPRODUCTLIST() {
        return new PRODUCTLIST();
    }

    /**
     * Create an instance of {@link PRODALPHA2 }
     * 
     */
    public PRODALPHA2 createPRODALPHA2() {
        return new PRODALPHA2();
    }

    /**
     * Create an instance of {@link SHOPLABELFIN }
     * 
     */
    public SHOPLABELFIN createSHOPLABELFIN() {
        return new SHOPLABELFIN();
    }

    /**
     * Create an instance of {@link CARACT }
     * 
     */
    public CARACT createCARACT() {
        return new CARACT();
    }

    /**
     * Create an instance of {@link CRITLIST }
     * 
     */
    public CRITLIST createCRITLIST() {
        return new CRITLIST();
    }

    /**
     * Create an instance of {@link PRODUCT }
     * 
     */
    public PRODUCT createPRODUCT() {
        return new PRODUCT();
    }

    /**
     * Create an instance of {@link PRODALPHA1 }
     * 
     */
    public PRODALPHA1 createPRODALPHA1() {
        return new PRODALPHA1();
    }

    /**
     * Create an instance of {@link SHOPLABELDEBUT }
     * 
     */
    public SHOPLABELDEBUT createSHOPLABELDEBUT() {
        return new SHOPLABELDEBUT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_EURO_FP")
    public JAXBElement<BigDecimal> createPRODEUROFP(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODEUROFP_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_VARS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSHOPVARS(String value) {
        return new JAXBElement<String>(_SHOPVARS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CARACT_LIST_COUNT")
    public JAXBElement<Integer> createCARACTLISTCOUNT(Integer value) {
        return new JAXBElement<Integer>(_CARACTLISTCOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_MEDIATION")
    public JAXBElement<Integer> createSHOPMEDIATION(Integer value) {
        return new JAXBElement<Integer>(_SHOPMEDIATION_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_COUNT")
    public JAXBElement<Integer> createSHOPCOUNT(Integer value) {
        return new JAXBElement<Integer>(_SHOPCOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_DISPO")
    public JAXBElement<String> createPRODDISPO(String value) {
        return new JAXBElement<String>(_PRODDISPO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_REF")
    public JAXBElement<String> createPRODREF(String value) {
        return new JAXBElement<String>(_PRODREF_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PRODUCT_LIST_COUNT")
    public JAXBElement<Integer> createPRODUCTLISTCOUNT(Integer value) {
        return new JAXBElement<Integer>(_PRODUCTLISTCOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BARRE_COUNT")
    public JAXBElement<Integer> createBARRECOUNT(Integer value) {
        return new JAXBElement<Integer>(_BARRECOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_PAYS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSHOPPAYS(String value) {
        return new JAXBElement<String>(_SHOPPAYS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GROUP_SOLDE")
    public JAXBElement<Integer> createGROUPSOLDE(Integer value) {
        return new JAXBElement<Integer>(_GROUPSOLDE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_PRIVE")
    public JAXBElement<Integer> createPRODPRIVE(Integer value) {
        return new JAXBElement<Integer>(_PRODPRIVE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_NAME")
    public JAXBElement<String> createSHOPNAME(String value) {
        return new JAXBElement<String>(_SHOPNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QUERY_ID")
    public JAXBElement<Long> createQUERYID(Long value) {
        return new JAXBElement<Long>(_QUERYID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_WITH_CARAC")
    public JAXBElement<Integer> createPRODWITHCARAC(Integer value) {
        return new JAXBElement<Integer>(_PRODWITHCARAC_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_LOGO")
    public JAXBElement<Integer> createSHOPLOGO(Integer value) {
        return new JAXBElement<Integer>(_SHOPLOGO_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CARACT_NAME")
    public JAXBElement<String> createCARACTNAME(String value) {
        return new JAXBElement<String>(_CARACTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CRIT_LIST_COUNT")
    public JAXBElement<Integer> createCRITLISTCOUNT(Integer value) {
        return new JAXBElement<Integer>(_CRITLISTCOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_LABEL_VALID")
    public JAXBElement<Integer> createSHOPLABELVALID(Integer value) {
        return new JAXBElement<Integer>(_SHOPLABELVALID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_GLOBAL")
    public JAXBElement<BigDecimal> createSHOPGLOBAL(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_SHOPGLOBAL_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OCCASE_COUNT")
    public JAXBElement<Integer> createOCCASECOUNT(Integer value) {
        return new JAXBElement<Integer>(_OCCASECOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_INTL_FP")
    public JAXBElement<BigDecimal> createPRODINTLFP(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODINTLFP_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OFFRE_COUNT")
    public JAXBElement<Integer> createOFFRECOUNT(Integer value) {
        return new JAXBElement<Integer>(_OFFRECOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_ID")
    public JAXBElement<Integer> createSHOPID(Integer value) {
        return new JAXBElement<Integer>(_SHOPID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_D3E")
    public JAXBElement<BigDecimal> createPRODD3E(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODD3E_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_BASE_ID")
    public JAXBElement<Integer> createPRODBASEID(Integer value) {
        return new JAXBElement<Integer>(_PRODBASEID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MARK_COUNT")
    public JAXBElement<Integer> createMARKCOUNT(Integer value) {
        return new JAXBElement<Integer>(_MARKCOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MARK_LIST_COUNT")
    public JAXBElement<Integer> createMARKLISTCOUNT(Integer value) {
        return new JAXBElement<Integer>(_MARKLISTCOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_INTL_DEVISE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPRODINTLDEVISE(String value) {
        return new JAXBElement<String>(_PRODINTLDEVISE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_DESCRIPTION")
    public JAXBElement<String> createPRODDESCRIPTION(String value) {
        return new JAXBElement<String>(_PRODDESCRIPTION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PRICE_LIST_COUNT")
    public JAXBElement<Integer> createPRICELISTCOUNT(Integer value) {
        return new JAXBElement<Integer>(_PRICELISTCOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_URL")
    public JAXBElement<String> createCATURL(String value) {
        return new JAXBElement<String>(_CATURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CARACT_VALUE")
    public JAXBElement<String> createCARACTVALUE(String value) {
        return new JAXBElement<String>(_CARACTVALUE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_SOLDE")
    public JAXBElement<Integer> createPRODSOLDE(Integer value) {
        return new JAXBElement<Integer>(_PRODSOLDE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_INTL_PRICE")
    public JAXBElement<BigDecimal> createPRODINTLPRICE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODINTLPRICE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PRODUCT_COUNT")
    public JAXBElement<Integer> createPRODUCTCOUNT(Integer value) {
        return new JAXBElement<Integer>(_PRODUCTCOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NEUF_COUNT")
    public JAXBElement<Integer> createNEUFCOUNT(Integer value) {
        return new JAXBElement<Integer>(_NEUFCOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CARACT_ID")
    public JAXBElement<Integer> createCARACTID(Integer value) {
        return new JAXBElement<Integer>(_CARACTID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PRIVE_COUNT")
    public JAXBElement<Integer> createPRIVECOUNT(Integer value) {
        return new JAXBElement<Integer>(_PRIVECOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_CAT_SHOP")
    public JAXBElement<String> createPRODCATSHOP(String value) {
        return new JAXBElement<String>(_PRODCATSHOP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_MARK")
    public JAXBElement<String> createPRODMARK(String value) {
        return new JAXBElement<String>(_PRODMARK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPRODID(String value) {
        return new JAXBElement<String>(_PRODID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_SINGLE_NAME")
    public JAXBElement<String> createCATSINGLENAME(String value) {
        return new JAXBElement<String>(_CATSINGLENAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_MASQUE")
    public JAXBElement<Integer> createPRODMASQUE(Integer value) {
        return new JAXBElement<Integer>(_PRODMASQUE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_REF_INTERNE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPRODREFINTERNE(String value) {
        return new JAXBElement<String>(_PRODREFINTERNE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_ID_INTERNE")
    public JAXBElement<Integer> createCATIDINTERNE(Integer value) {
        return new JAXBElement<Integer>(_CATIDINTERNE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SOLDE_COUNT")
    public JAXBElement<Integer> createSOLDECOUNT(Integer value) {
        return new JAXBElement<Integer>(_SOLDECOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PAGE_COUNT")
    public JAXBElement<Integer> createPAGECOUNT(Integer value) {
        return new JAXBElement<Integer>(_PAGECOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_ID")
    public JAXBElement<Integer> createCATID(Integer value) {
        return new JAXBElement<Integer>(_CATID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_URL")
    public JAXBElement<String> createPRODURL(String value) {
        return new JAXBElement<String>(_PRODURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_GARANTIE")
    public JAXBElement<Integer> createPRODGARANTIE(Integer value) {
        return new JAXBElement<Integer>(_PRODGARANTIE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_DESIGNATION")
    public JAXBElement<String> createPRODDESIGNATION(String value) {
        return new JAXBElement<String>(_PRODDESIGNATION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PRICE_MIN")
    public JAXBElement<BigDecimal> createPRICEMIN(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRICEMIN_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_EURO_DISCOUNT")
    public JAXBElement<BigDecimal> createPRODEURODISCOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODEURODISCOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_OCCASION")
    public JAXBElement<Integer> createPRODOCCASION(Integer value) {
        return new JAXBElement<Integer>(_PRODOCCASION_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PRICE_MAX")
    public JAXBElement<BigDecimal> createPRICEMAX(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRICEMAX_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_EAN13")
    public JAXBElement<String> createPRODEAN13(String value) {
        return new JAXBElement<String>(_PRODEAN13_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_EURO_PRICE")
    public JAXBElement<BigDecimal> createPRODEUROPRICE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODEUROPRICE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_DISPO_NAME")
    public JAXBElement<String> createPRODDISPONAME(String value) {
        return new JAXBElement<String>(_PRODDISPONAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TOTAL_PRODUCT_COUNT")
    public JAXBElement<Integer> createTOTALPRODUCTCOUNT(Integer value) {
        return new JAXBElement<Integer>(_TOTALPRODUCTCOUNT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_IMG")
    public JAXBElement<String> createPRODIMG(String value) {
        return new JAXBElement<String>(_PRODIMG_QNAME, String.class, null, value);
    }

}
