//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.22 at 05:45:26 PM CEST 
//


package com.leguide.backoffice.karaf.webservices.client.engine.domain.response.listeOffers;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{com.leguide.mobile.xsd.response}Response">
 *       &lt;sequence>
 *         &lt;element ref="{}QUERY_ID"/>
 *         &lt;element ref="{}TOTAL_PRODUCT_COUNT"/>
 *         &lt;element ref="{}PRODUCT_COUNT"/>
 *         &lt;element ref="{}NEUF_COUNT"/>
 *         &lt;element ref="{}OCCASE_COUNT"/>
 *         &lt;element ref="{}SOLDE_COUNT"/>
 *         &lt;element ref="{}PRIVE_COUNT"/>
 *         &lt;element ref="{}BARRE_COUNT"/>
 *         &lt;element ref="{}PAGE_COUNT"/>
 *         &lt;element ref="{}PROD_BASE_ID"/>
 *         &lt;element ref="{}PROD_MARK"/>
 *         &lt;element ref="{}PROD_REF"/>
 *         &lt;element ref="{}PROD_IMG"/>
 *         &lt;element ref="{}CAT_ID_INTERNE"/>
 *         &lt;element ref="{}CAT_ID"/>
 *         &lt;element ref="{}CAT_SINGLE_NAME"/>
 *         &lt;element ref="{}CAT_URL"/>
 *         &lt;element ref="{}OFFRE_COUNT"/>
 *         &lt;element ref="{}SHOP_COUNT"/>
 *         &lt;element ref="{}PRICE_MIN"/>
 *         &lt;element ref="{}PRICE_MAX"/>
 *         &lt;element ref="{}GROUP_SOLDE"/>
 *         &lt;element ref="{}PRICE_LIST_COUNT"/>
 *         &lt;element ref="{}PRICE_LIST"/>
 *         &lt;element ref="{}MARK_COUNT"/>
 *         &lt;element ref="{}MARK_LIST_COUNT"/>
 *         &lt;element ref="{}MARK_LIST"/>
 *         &lt;element ref="{}CRIT_LIST_COUNT"/>
 *         &lt;element ref="{}CRIT_LIST"/>
 *         &lt;element ref="{}CARACT_LIST_COUNT"/>
 *         &lt;element ref="{}CARACT_LIST"/>
 *         &lt;element ref="{}PRODUCT_LIST_COUNT"/>
 *         &lt;element ref="{}PRODUCT_LIST"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryid",
    "totalproductcount",
    "productcount",
    "neufcount",
    "occasecount",
    "soldecount",
    "privecount",
    "barrecount",
    "pagecount",
    "prodbaseid",
    "prodmark",
    "prodref",
    "prodimg",
    "catidinterne",
    "catid",
    "catsinglename",
    "caturl",
    "offrecount",
    "shopcount",
    "pricemin",
    "pricemax",
    "groupsolde",
    "pricelistcount",
    "pricelist",
    "markcount",
    "marklistcount",
    "marklist",
    "critlistcount",
    "critlist",
    "caractlistcount",
    "caractlist",
    "productlistcount",
    "productlist"
})
@XmlRootElement(name = "RESULTAT")
public class RESULTAT
    extends Response
{

    @XmlElement(name = "QUERY_ID")
    protected long queryid;
    @XmlElement(name = "TOTAL_PRODUCT_COUNT")
    protected int totalproductcount;
    @XmlElement(name = "PRODUCT_COUNT")
    protected int productcount;
    @XmlElement(name = "NEUF_COUNT")
    protected int neufcount;
    @XmlElement(name = "OCCASE_COUNT")
    protected int occasecount;
    @XmlElement(name = "SOLDE_COUNT")
    protected int soldecount;
    @XmlElement(name = "PRIVE_COUNT")
    protected int privecount;
    @XmlElement(name = "BARRE_COUNT")
    protected int barrecount;
    @XmlElement(name = "PAGE_COUNT")
    protected int pagecount;
    @XmlElement(name = "PROD_BASE_ID")
    protected int prodbaseid;
    @XmlElement(name = "PROD_MARK", required = true)
    protected String prodmark;
    @XmlElement(name = "PROD_REF", required = true)
    protected String prodref;
    @XmlElement(name = "PROD_IMG", required = true)
    protected String prodimg;
    @XmlElement(name = "CAT_ID_INTERNE")
    protected int catidinterne;
    @XmlElement(name = "CAT_ID")
    protected int catid;
    @XmlElement(name = "CAT_SINGLE_NAME", required = true)
    protected String catsinglename;
    @XmlElement(name = "CAT_URL", required = true)
    protected String caturl;
    @XmlElement(name = "OFFRE_COUNT")
    protected int offrecount;
    @XmlElement(name = "SHOP_COUNT")
    protected int shopcount;
    @XmlElement(name = "PRICE_MIN", required = true)
    protected BigDecimal pricemin;
    @XmlElement(name = "PRICE_MAX", required = true)
    protected BigDecimal pricemax;
    @XmlElement(name = "GROUP_SOLDE")
    protected int groupsolde;
    @XmlElement(name = "PRICE_LIST_COUNT")
    protected int pricelistcount;
    @XmlElement(name = "PRICE_LIST", required = true)
    protected PRICELIST pricelist;
    @XmlElement(name = "MARK_COUNT")
    protected int markcount;
    @XmlElement(name = "MARK_LIST_COUNT")
    protected int marklistcount;
    @XmlElement(name = "MARK_LIST", required = true)
    protected MARKLIST marklist;
    @XmlElement(name = "CRIT_LIST_COUNT")
    protected int critlistcount;
    @XmlElement(name = "CRIT_LIST", required = true)
    protected CRITLIST critlist;
    @XmlElement(name = "CARACT_LIST_COUNT")
    protected int caractlistcount;
    @XmlElement(name = "CARACT_LIST", required = true)
    protected CARACTLIST caractlist;
    @XmlElement(name = "PRODUCT_LIST_COUNT")
    protected int productlistcount;
    @XmlElement(name = "PRODUCT_LIST", required = true)
    protected PRODUCTLIST productlist;

    /**
     * Gets the value of the queryid property.
     * 
     */
    public long getQUERYID() {
        return queryid;
    }

    /**
     * Sets the value of the queryid property.
     * 
     */
    public void setQUERYID(long value) {
        this.queryid = value;
    }

    /**
     * Gets the value of the totalproductcount property.
     * 
     */
    public int getTOTALPRODUCTCOUNT() {
        return totalproductcount;
    }

    /**
     * Sets the value of the totalproductcount property.
     * 
     */
    public void setTOTALPRODUCTCOUNT(int value) {
        this.totalproductcount = value;
    }

    /**
     * Gets the value of the productcount property.
     * 
     */
    public int getPRODUCTCOUNT() {
        return productcount;
    }

    /**
     * Sets the value of the productcount property.
     * 
     */
    public void setPRODUCTCOUNT(int value) {
        this.productcount = value;
    }

    /**
     * Gets the value of the neufcount property.
     * 
     */
    public int getNEUFCOUNT() {
        return neufcount;
    }

    /**
     * Sets the value of the neufcount property.
     * 
     */
    public void setNEUFCOUNT(int value) {
        this.neufcount = value;
    }

    /**
     * Gets the value of the occasecount property.
     * 
     */
    public int getOCCASECOUNT() {
        return occasecount;
    }

    /**
     * Sets the value of the occasecount property.
     * 
     */
    public void setOCCASECOUNT(int value) {
        this.occasecount = value;
    }

    /**
     * Gets the value of the soldecount property.
     * 
     */
    public int getSOLDECOUNT() {
        return soldecount;
    }

    /**
     * Sets the value of the soldecount property.
     * 
     */
    public void setSOLDECOUNT(int value) {
        this.soldecount = value;
    }

    /**
     * Gets the value of the privecount property.
     * 
     */
    public int getPRIVECOUNT() {
        return privecount;
    }

    /**
     * Sets the value of the privecount property.
     * 
     */
    public void setPRIVECOUNT(int value) {
        this.privecount = value;
    }

    /**
     * Gets the value of the barrecount property.
     * 
     */
    public int getBARRECOUNT() {
        return barrecount;
    }

    /**
     * Sets the value of the barrecount property.
     * 
     */
    public void setBARRECOUNT(int value) {
        this.barrecount = value;
    }

    /**
     * Gets the value of the pagecount property.
     * 
     */
    public int getPAGECOUNT() {
        return pagecount;
    }

    /**
     * Sets the value of the pagecount property.
     * 
     */
    public void setPAGECOUNT(int value) {
        this.pagecount = value;
    }

    /**
     * Gets the value of the prodbaseid property.
     * 
     */
    public int getPRODBASEID() {
        return prodbaseid;
    }

    /**
     * Sets the value of the prodbaseid property.
     * 
     */
    public void setPRODBASEID(int value) {
        this.prodbaseid = value;
    }

    /**
     * Gets the value of the prodmark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODMARK() {
        return prodmark;
    }

    /**
     * Sets the value of the prodmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODMARK(String value) {
        this.prodmark = value;
    }

    /**
     * Gets the value of the prodref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODREF() {
        return prodref;
    }

    /**
     * Sets the value of the prodref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODREF(String value) {
        this.prodref = value;
    }

    /**
     * Gets the value of the prodimg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODIMG() {
        return prodimg;
    }

    /**
     * Sets the value of the prodimg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODIMG(String value) {
        this.prodimg = value;
    }

    /**
     * Gets the value of the catidinterne property.
     * 
     */
    public int getCATIDINTERNE() {
        return catidinterne;
    }

    /**
     * Sets the value of the catidinterne property.
     * 
     */
    public void setCATIDINTERNE(int value) {
        this.catidinterne = value;
    }

    /**
     * Gets the value of the catid property.
     * 
     */
    public int getCATID() {
        return catid;
    }

    /**
     * Sets the value of the catid property.
     * 
     */
    public void setCATID(int value) {
        this.catid = value;
    }

    /**
     * Gets the value of the catsinglename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCATSINGLENAME() {
        return catsinglename;
    }

    /**
     * Sets the value of the catsinglename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCATSINGLENAME(String value) {
        this.catsinglename = value;
    }

    /**
     * Gets the value of the caturl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCATURL() {
        return caturl;
    }

    /**
     * Sets the value of the caturl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCATURL(String value) {
        this.caturl = value;
    }

    /**
     * Gets the value of the offrecount property.
     * 
     */
    public int getOFFRECOUNT() {
        return offrecount;
    }

    /**
     * Sets the value of the offrecount property.
     * 
     */
    public void setOFFRECOUNT(int value) {
        this.offrecount = value;
    }

    /**
     * Gets the value of the shopcount property.
     * 
     */
    public int getSHOPCOUNT() {
        return shopcount;
    }

    /**
     * Sets the value of the shopcount property.
     * 
     */
    public void setSHOPCOUNT(int value) {
        this.shopcount = value;
    }

    /**
     * Gets the value of the pricemin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICEMIN() {
        return pricemin;
    }

    /**
     * Sets the value of the pricemin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICEMIN(BigDecimal value) {
        this.pricemin = value;
    }

    /**
     * Gets the value of the pricemax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICEMAX() {
        return pricemax;
    }

    /**
     * Sets the value of the pricemax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICEMAX(BigDecimal value) {
        this.pricemax = value;
    }

    /**
     * Gets the value of the groupsolde property.
     * 
     */
    public int getGROUPSOLDE() {
        return groupsolde;
    }

    /**
     * Sets the value of the groupsolde property.
     * 
     */
    public void setGROUPSOLDE(int value) {
        this.groupsolde = value;
    }

    /**
     * Gets the value of the pricelistcount property.
     * 
     */
    public int getPRICELISTCOUNT() {
        return pricelistcount;
    }

    /**
     * Sets the value of the pricelistcount property.
     * 
     */
    public void setPRICELISTCOUNT(int value) {
        this.pricelistcount = value;
    }

    /**
     * Gets the value of the pricelist property.
     * 
     * @return
     *     possible object is
     *     {@link PRICELIST }
     *     
     */
    public PRICELIST getPRICELIST() {
        return pricelist;
    }

    /**
     * Sets the value of the pricelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICELIST }
     *     
     */
    public void setPRICELIST(PRICELIST value) {
        this.pricelist = value;
    }

    /**
     * Gets the value of the markcount property.
     * 
     */
    public int getMARKCOUNT() {
        return markcount;
    }

    /**
     * Sets the value of the markcount property.
     * 
     */
    public void setMARKCOUNT(int value) {
        this.markcount = value;
    }

    /**
     * Gets the value of the marklistcount property.
     * 
     */
    public int getMARKLISTCOUNT() {
        return marklistcount;
    }

    /**
     * Sets the value of the marklistcount property.
     * 
     */
    public void setMARKLISTCOUNT(int value) {
        this.marklistcount = value;
    }

    /**
     * Gets the value of the marklist property.
     * 
     * @return
     *     possible object is
     *     {@link MARKLIST }
     *     
     */
    public MARKLIST getMARKLIST() {
        return marklist;
    }

    /**
     * Sets the value of the marklist property.
     * 
     * @param value
     *     allowed object is
     *     {@link MARKLIST }
     *     
     */
    public void setMARKLIST(MARKLIST value) {
        this.marklist = value;
    }

    /**
     * Gets the value of the critlistcount property.
     * 
     */
    public int getCRITLISTCOUNT() {
        return critlistcount;
    }

    /**
     * Sets the value of the critlistcount property.
     * 
     */
    public void setCRITLISTCOUNT(int value) {
        this.critlistcount = value;
    }

    /**
     * Gets the value of the critlist property.
     * 
     * @return
     *     possible object is
     *     {@link CRITLIST }
     *     
     */
    public CRITLIST getCRITLIST() {
        return critlist;
    }

    /**
     * Sets the value of the critlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRITLIST }
     *     
     */
    public void setCRITLIST(CRITLIST value) {
        this.critlist = value;
    }

    /**
     * Gets the value of the caractlistcount property.
     * 
     */
    public int getCARACTLISTCOUNT() {
        return caractlistcount;
    }

    /**
     * Sets the value of the caractlistcount property.
     * 
     */
    public void setCARACTLISTCOUNT(int value) {
        this.caractlistcount = value;
    }

    /**
     * Gets the value of the caractlist property.
     * 
     * @return
     *     possible object is
     *     {@link CARACTLIST }
     *     
     */
    public CARACTLIST getCARACTLIST() {
        return caractlist;
    }

    /**
     * Sets the value of the caractlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link CARACTLIST }
     *     
     */
    public void setCARACTLIST(CARACTLIST value) {
        this.caractlist = value;
    }

    /**
     * Gets the value of the productlistcount property.
     * 
     */
    public int getPRODUCTLISTCOUNT() {
        return productlistcount;
    }

    /**
     * Sets the value of the productlistcount property.
     * 
     */
    public void setPRODUCTLISTCOUNT(int value) {
        this.productlistcount = value;
    }

    /**
     * Gets the value of the productlist property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTLIST }
     *     
     */
    public PRODUCTLIST getPRODUCTLIST() {
        return productlist;
    }

    /**
     * Sets the value of the productlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTLIST }
     *     
     */
    public void setPRODUCTLIST(PRODUCTLIST value) {
        this.productlist = value;
    }

}
