//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.22 at 05:45:26 PM CEST 
//


package com.leguide.backoffice.karaf.webservices.client.engine.model.response.productInfo;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.leguide.backoffice.karaf.webservices.client.engine.model.response.productInfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PRODEUROFP_QNAME = new QName("", "PROD_EURO_FP");
    private final static QName _PRODINTLDEVISE_QNAME = new QName("", "PROD_INTL_DEVISE");
    private final static QName _CATURL_QNAME = new QName("", "CAT_URL");
    private final static QName _PRODDESCRIPTION_QNAME = new QName("", "PROD_DESCRIPTION");
    private final static QName _PRODSOLDE_QNAME = new QName("", "PROD_SOLDE");
    private final static QName _SHOPVARS_QNAME = new QName("", "SHOP_VARS");
    private final static QName _PRODINTLPRICE_QNAME = new QName("", "PROD_INTL_PRICE");
    private final static QName _SHOPMEDIATION_QNAME = new QName("", "SHOP_MEDIATION");
    private final static QName _PRODCATSHOP_QNAME = new QName("", "PROD_CAT_SHOP");
    private final static QName _PRODMARK_QNAME = new QName("", "PROD_MARK");
    private final static QName _PRODDISPO_QNAME = new QName("", "PROD_DISPO");
    private final static QName _SHOPPAYS_QNAME = new QName("", "SHOP_PAYS");
    private final static QName _PRODID_QNAME = new QName("", "PROD_ID");
    private final static QName _CATSINGLENAME_QNAME = new QName("", "CAT_SINGLE_NAME");
    private final static QName _PRODPRIVE_QNAME = new QName("", "PROD_PRIVE");
    private final static QName _PRODMASQUE_QNAME = new QName("", "PROD_MASQUE");
    private final static QName _PRODREFINTERNE_QNAME = new QName("", "PROD_REF_INTERNE");
    private final static QName _SHOPNAME_QNAME = new QName("", "SHOP_NAME");
    private final static QName _PRODWITHCARAC_QNAME = new QName("", "PROD_WITH_CARAC");
    private final static QName _CATIDINTERNE_QNAME = new QName("", "CAT_ID_INTERNE");
    private final static QName _SHOPLOGO_QNAME = new QName("", "SHOP_LOGO");
    private final static QName _CATID_QNAME = new QName("", "CAT_ID");
    private final static QName _PRODURL_QNAME = new QName("", "PROD_URL");
    private final static QName _PRODGARANTIE_QNAME = new QName("", "PROD_GARANTIE");
    private final static QName _SHOPLABELVALID_QNAME = new QName("", "SHOP_LABEL_VALID");
    private final static QName _SHOPGLOBAL_QNAME = new QName("", "SHOP_GLOBAL");
    private final static QName _PRODDESIGNATION_QNAME = new QName("", "PROD_DESIGNATION");
    private final static QName _PRODOCCASION_QNAME = new QName("", "PROD_OCCASION");
    private final static QName _PRODEURODISCOUNT_QNAME = new QName("", "PROD_EURO_DISCOUNT");
    private final static QName _PRODINTLFP_QNAME = new QName("", "PROD_INTL_FP");
    private final static QName _SHOPID_QNAME = new QName("", "SHOP_ID");
    private final static QName _PRODD3E_QNAME = new QName("", "PROD_D3E");
    private final static QName _PRODBASEID_QNAME = new QName("", "PROD_BASE_ID");
    private final static QName _PRODEUROPRICE_QNAME = new QName("", "PROD_EURO_PRICE");
    private final static QName _PRODDISPONAME_QNAME = new QName("", "PROD_DISPO_NAME");
    private final static QName _PRODIMG_QNAME = new QName("", "PROD_IMG");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.leguide.backoffice.karaf.webservices.client.engine.model.response.productInfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PRODREF }
     * 
     */
    public PRODREF createPRODREF() {
        return new PRODREF();
    }

    /**
     * Create an instance of {@link PRODEAN13 }
     * 
     */
    public PRODEAN13 createPRODEAN13() {
        return new PRODEAN13();
    }

    /**
     * Create an instance of {@link PRODALPHA2 }
     * 
     */
    public PRODALPHA2 createPRODALPHA2() {
        return new PRODALPHA2();
    }

    /**
     * Create an instance of {@link RESULTATPI }
     * 
     */
    public RESULTATPI createRESULTATPI() {
        return new RESULTATPI();
    }

    /**
     * Create an instance of {@link PRODALPHA1 }
     * 
     */
    public PRODALPHA1 createPRODALPHA1() {
        return new PRODALPHA1();
    }

    /**
     * Create an instance of {@link PRODUCT }
     * 
     */
    public PRODUCT createPRODUCT() {
        return new PRODUCT();
    }

    /**
     * Create an instance of {@link SHOPLABELFIN }
     * 
     */
    public SHOPLABELFIN createSHOPLABELFIN() {
        return new SHOPLABELFIN();
    }

    /**
     * Create an instance of {@link SHOPLABELDEBUT }
     * 
     */
    public SHOPLABELDEBUT createSHOPLABELDEBUT() {
        return new SHOPLABELDEBUT();
    }

    /**
     * Create an instance of {@link PRODEXTRAS }
     * 
     */
    public PRODEXTRAS createPRODEXTRAS() {
        return new PRODEXTRAS();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_EURO_FP")
    public JAXBElement<BigDecimal> createPRODEUROFP(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODEUROFP_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_INTL_DEVISE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPRODINTLDEVISE(String value) {
        return new JAXBElement<String>(_PRODINTLDEVISE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_URL")
    public JAXBElement<String> createCATURL(String value) {
        return new JAXBElement<String>(_CATURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_DESCRIPTION")
    public JAXBElement<String> createPRODDESCRIPTION(String value) {
        return new JAXBElement<String>(_PRODDESCRIPTION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_SOLDE")
    public JAXBElement<BigInteger> createPRODSOLDE(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODSOLDE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_VARS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSHOPVARS(String value) {
        return new JAXBElement<String>(_SHOPVARS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_INTL_PRICE")
    public JAXBElement<BigDecimal> createPRODINTLPRICE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODINTLPRICE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_MEDIATION")
    public JAXBElement<BigInteger> createSHOPMEDIATION(BigInteger value) {
        return new JAXBElement<BigInteger>(_SHOPMEDIATION_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_CAT_SHOP")
    public JAXBElement<String> createPRODCATSHOP(String value) {
        return new JAXBElement<String>(_PRODCATSHOP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_MARK")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPRODMARK(String value) {
        return new JAXBElement<String>(_PRODMARK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_DISPO")
    public JAXBElement<BigInteger> createPRODDISPO(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODDISPO_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_PAYS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSHOPPAYS(String value) {
        return new JAXBElement<String>(_SHOPPAYS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_ID")
    public JAXBElement<BigInteger> createPRODID(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_SINGLE_NAME")
    public JAXBElement<String> createCATSINGLENAME(String value) {
        return new JAXBElement<String>(_CATSINGLENAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_PRIVE")
    public JAXBElement<BigInteger> createPRODPRIVE(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODPRIVE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_MASQUE")
    public JAXBElement<BigInteger> createPRODMASQUE(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODMASQUE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_REF_INTERNE")
    public JAXBElement<BigInteger> createPRODREFINTERNE(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODREFINTERNE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_NAME")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSHOPNAME(String value) {
        return new JAXBElement<String>(_SHOPNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_WITH_CARAC")
    public JAXBElement<BigInteger> createPRODWITHCARAC(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODWITHCARAC_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_ID_INTERNE")
    public JAXBElement<BigInteger> createCATIDINTERNE(BigInteger value) {
        return new JAXBElement<BigInteger>(_CATIDINTERNE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_LOGO")
    public JAXBElement<BigInteger> createSHOPLOGO(BigInteger value) {
        return new JAXBElement<BigInteger>(_SHOPLOGO_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_ID")
    public JAXBElement<BigInteger> createCATID(BigInteger value) {
        return new JAXBElement<BigInteger>(_CATID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_URL")
    public JAXBElement<String> createPRODURL(String value) {
        return new JAXBElement<String>(_PRODURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_GARANTIE")
    public JAXBElement<BigInteger> createPRODGARANTIE(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODGARANTIE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_LABEL_VALID")
    public JAXBElement<BigInteger> createSHOPLABELVALID(BigInteger value) {
        return new JAXBElement<BigInteger>(_SHOPLABELVALID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_GLOBAL")
    public JAXBElement<BigDecimal> createSHOPGLOBAL(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_SHOPGLOBAL_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_DESIGNATION")
    public JAXBElement<String> createPRODDESIGNATION(String value) {
        return new JAXBElement<String>(_PRODDESIGNATION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_OCCASION")
    public JAXBElement<BigInteger> createPRODOCCASION(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODOCCASION_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_EURO_DISCOUNT")
    public JAXBElement<BigDecimal> createPRODEURODISCOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODEURODISCOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_INTL_FP")
    public JAXBElement<BigDecimal> createPRODINTLFP(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODINTLFP_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHOP_ID")
    public JAXBElement<BigInteger> createSHOPID(BigInteger value) {
        return new JAXBElement<BigInteger>(_SHOPID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_D3E")
    public JAXBElement<BigInteger> createPRODD3E(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODD3E_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_BASE_ID")
    public JAXBElement<BigInteger> createPRODBASEID(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODBASEID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_EURO_PRICE")
    public JAXBElement<BigDecimal> createPRODEUROPRICE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PRODEUROPRICE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_DISPO_NAME")
    public JAXBElement<BigInteger> createPRODDISPONAME(BigInteger value) {
        return new JAXBElement<BigInteger>(_PRODDISPONAME_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROD_IMG")
    public JAXBElement<String> createPRODIMG(String value) {
        return new JAXBElement<String>(_PRODIMG_QNAME, String.class, null, value);
    }

}
